theme: jekyll-theme-cayman
download_win: https://www.dropbox.com/s/0m9h35oztws9ujb/Robota_final.zip?dl=0
download_mac: https://www.dropbox.com/s/npznn0ctt84j3wy/Robota_mac.app.zip?dl=0
title: Robota - The Fourth Law
description: Robota - The Fourth Law was developed as part of the Computer Games Development course 2017/18 at the Faculty of Mathematics and Physics, Charles University Prague
